# Generated by Django 2.0.8 on 2019-04-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clickevent',
            old_name='kirr_url',
            new_name='fella_url',
        ),
    ]
