# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-11 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_short', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellaurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
