# Generated by Django 2.0.8 on 2019-04-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_short', '0002_auto_20190411_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellaurl',
            name='url',
            field=models.URLField(max_length=250),
        ),
    ]
